"""empty message

Revision ID: 112681ac2784
Revises: 
Create Date: 2024-11-09 15:42:05.537165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112681ac2784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bicycle', sa.String(length=200), nullable=False),
    sa.Column('lost_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lng', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('lost_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lost_id'], ['lost.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatting')
    op.drop_table('lost')
    # ### end Alembic commands ###
